services:
  - type: web
    name: your-service-name
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
